---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tactical-data
  namespace: tacticalrmm
  labels:
    app: tacticalrmm
    service: tactical-data

spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 200Mi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mesh-data
  namespace: tacticalrmm
  labels:
    app: tacticalrmm
    service: mesh-data

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
  namespace: tacticalrmm
  labels:
    app: tacticalrmm
    service: mongo-data

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-data
  namespace: tacticalrmm
  labels:
    app: tacticalrmm
    service: redis-data

spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
status: {}
